version = 0.1

[default.deploy.parameters]
stack_name = "schedule-live"
resolve_s3 = true
s3_prefix = "schedule-live"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CorsOrigin=\"*\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
